services:
  library_container:
    container_name: library_container
    build:
      context: .
      dockerfile: ./tmp.ruby.dockerfile
      args:
        - RUBY_VERSION=3.3.6
        - GEM_VERSION=3.5.23
    tty: true
    restart: on-failure
    volumes:
      - ../:/usr/src/app